let data = [
    {
        "country": "uruguay",
        "year": 1930,
        "text": "The 1930 FIFA World Cup was the inaugural FIFA World Cup, the world championship for men's national football teams. It took place in Uruguay from 13 to 30 July 1930. FIFA, football's international governing body, selected Uruguay as host nation, as the country would be celebrating the centenary of its first constitution and the Uruguay national football team had successfully retained their football title at the 1928 Summer Olympics. All matches were played in the Uruguayan capital, Montevideo, the majority at the Estadio Centenario, which was built for the tournament.Thirteen teams (seven from South America, four from Europe, and two from North America) entered the tournament. Only a few European teams chose to participate because of the difficulty of traveling to South America due to an economic crisis. The teams were divided into four groups, with the winner of each group progressing to the semi-finals. The first two World Cup matches took place simultaneously and were won by France and the United States, who defeated Mexico 4–1 and Belgium 3–0, respectively. Lucien Laurent of France scored the first goal in World Cup history, while United States goalkeeper Jimmy Douglas posted the first clean sheet in the tournament the same day.Argentina, Uruguay, the United States, and Yugoslavia won their respective groups to qualify for the semi-finals. In the final, hosts and pre-tournament favourites Uruguay defeated Argentina 4–2 in front of 68,346 people to become the first nation to win the World Cup.",
        "url" : "../image/uruguay.png"
    },
    {
        "country": "Italy",
        "year": 1934,
        "text": "The 1934 FIFA World Cup was the second edition of the FIFA World Cup, the quadrennial international football championship for senior men's national teams. It took place in Italy from 27 May to 10 June 1934. The 1934 World Cup was the first in which teams had to qualify to take part. Thirty-two nations entered the competition; 16 teams would qualify for the final tournament. Reigning champions Uruguay boycotted the tournament as only four European teams had accepted their invitation to the 1930 tournament. Italy beat Czechoslovakia 2–1 to become the second World Cup champions and the first European winners. The 1934 World Cup was marred by being a high-profile instance of a sporting event being used for overt political gain. In particular, Benito Mussolini was keen to use this World Cup as a means of promoting fascism. Although some historians and sports journalists have made accusations of corruption and meddling by Mussolini to influence the competition to the benefit of Italy,Italy has always claimed to have deserved victory in the competition and the successful national team, considered to be one of the best in the country's history, emerged victorious also in the Olympic football tournament of 1936 hosted by Germany and in the 1938 World Cup hosted by France. The Federale 102 ball, which was manufactured in Italy, was the match ball provided for the 1934 World Cup.",
        "url": "../image/italy.png"
    },
    {
        "country": "Italy",
        "year": 1938,
        "text": "The 1938 FIFA World Cup was the third edition of the World Cup, the quadrennial international football championship for senior men's national teams and was held in France from 4 June until 19 June 1938. Italy defended its title in the final, beating Hungary 4–2. Italy's 1934 and 1938 teams hold the distinction of being the only men's national team to win the World Cup multiple times under the same coach, Vittorio Pozzo. It would be the last World Cup until 1950 due to the disruption from World War II.",
        "url": "../image/italy.png"
    },
    {
        "country": "Uruguay",
        "year": 1950,
        "text": "The 1950 FIFA World Cup was the fourth edition of the FIFA World Cup, the quadrennial international football championship for senior men's national teams and held in Brazil from 24 June to 16 July 1950. The planned 1942 and 1946 World Cups were cancelled due to World War II. This tournament ended the hiatus. Uruguay, who had won the inaugural competition in 1930, defeated the host nation, Brazil, in the deciding match of the four-team group of the final round. This was the only tournament not decided by a one-match final. It was also the inaugural tournament where the trophy was referred to as the Jules Rimet Cup, to mark the 25th anniversary of Jules Rimet's presidency of FIFA.",
        "url": "../image/uruguay.png"
    },
    {
        "country": "Germany",
        "year": 1954,
        "text": "The 1954 FIFA World Cup was the fifth edition of the FIFA World Cup, the quadrennial international football tournament for senior men's national teams of the nations affiliated to FIFA. It was held in Switzerland from 16 June to 4 July. Switzerland was selected as the host country in July 1946. At the tournament several all-time records for goal-scoring were set, including the highest average number of goals scored per game. The tournament was won by West Germany, who defeated tournament favourites Hungary 3–2 in the final, their first World Cup title.",
        "url": "../image/germany.png"
    },
    {
        "country": "Brazil",
        "year": 1958,
        "text": "The 1958 FIFA World Cup was the sixth FIFA World Cup, a quadrennial football tournament for men's senior national teams, and was played in Sweden from 8 to 29 June 1958. It was the first FIFA World Cup to be played in a Nordic country.Brazil beat Sweden 5–2 in the final in Solna, Stockholm, to claim their first title, having beaten France in the semi final and Wales in the quarter final. The tournament also marked the arrival of a then 17-year-old Pelé on the world stage, who scored in all three of Brazil's knockout games. This was the first appearance of Wales at the FIFA World Cup and they would not qualify for another until 64 years later. This tournament also marked the debuts of fellow British side Northern Ireland, as well as the Soviet Union.",
        "url": "../image/brazil.png"
    },
    {
        "country": "Brazil",
        "year": 1962,
        "text": "The 1962 FIFA World Cup was the seventh edition of the FIFA World Cup, the quadrennial international football championship for senior men's national teams. It was held from 30 May to 17 June 1962 in Chile. The qualification rounds took place between August 1960 and December 1961, with 56 teams entering from six confederations, and fourteen qualifying for the finals tournament alongside Chile, the hosts, and Brazil, the defending champions. Brazil successfully defended their World Cup title, defeating Czechoslovakia 3–1 in the final in the Chilean capital of Santiago. They became the second team, after Italy in 1934 and 1938, to win the World Cup twice consecutively; no team has since achieved the feat. Host nation Chile finished third, defeating Yugoslavia 1–0 in the third-place play-off.The tournament was marred by violence between players on the pitch and a toxic atmosphere; it included the first-round match between Chile and Italy (2–0), which became known as the Battle of Santiago, one of a number of violent matches played throughout the tournament. It was the first World Cup that used goal average as a means of separating teams with the same number of points. It was also the first World Cup in which the average number of goals per match was less than three (2.78); this has been repeated at every World Cup since, despite expansion of the tournament.",
        "url": "../image/brazil.png"
    },
    {
        "country": "England",
        "year": 1966,
        "text": "The 1966 FIFA World Cup was the eighth FIFA World Cup, a quadrennial football tournament for men's senior national teams. It was played in England from 11 July to 30 July 1966. The England national football team defeated West Germany 4–2 in the final to win the tournament. The final had finished at 2–2 after 90 minutes and went to extra time, when Geoff Hurst scored two goals to complete his hat-trick, the first to be scored in a men's World Cup final. England were the fifth nation to win the event, and the third host nation to win after Uruguay in 1930 and Italy in 1934. Brazil were the defending champions, but they failed to progress from the group stage. Two debut teams performed well at the competition – North Korea beat Italy 1–0 on the way to reaching the quarter-finals, where they lost to Portugal 5–3 after leading 3–0. Portugal themselves finished third, losing 2–1 to England in the semi-final. Portuguese striker Eusébio was the tournament's top scorer, with nine goals clinching the golden boot with three goals more than second placed Helmut Haller.The 1966 World Cup was the first FIFA World Cup held in the English-speaking world. Matches were played at eight stadiums across England, with the final being held at Wembley Stadium, which had a capacity of 98,600. The 1966 event featured the highest number of teams of any international tournament to date, with 70 nations participating.All 15 African nations who entered the qualifying later boycotted the tournament in protest after FIFA, citing competitive and logistical issues, ruled that there would be no direct qualification for an African team. Prior to the tournament, the Jules Rimet trophy was stolen, but was recovered by a dog named Pickles four months before the tournament began. It was the first World Cup to have selected matches broadcast via satellite to countries on other continents. The final, which was broadcast locally by the BBC, was the last to be shown entirely in black and white.",
        "url": "../image/england.png"
    },
    {
        "country": "Brazil",
        "year": 1970,
        "text": "The 1970 FIFA World Cup was the ninth edition of the FIFA World Cup, the quadrennial international football championship for men's senior national teams. Held from 31 May to 21 June in Mexico, it was the first World Cup tournament held outside Europe and South America, and it was also the first held in North America. Teams representing 75 nations from all six populated continents entered the competition, and its qualification rounds began in May 1968. Fourteen teams qualified from this process to join host nation Mexico and defending champions England in the 16-team final tournament. El Salvador, Israel and Morocco made their debut appearances at the final stage. The tournament final had Brazil battle Italy, another FIFA two-time champion (and UEFA Euro 1968 winner), 4–1. Furthermore, during the tournament, Brazil also had to defeat another two-time champion (who were) South American champions Uruguay, by 3–1 in the semi-final, and defending champions England 1–0 in the group stage. This is currently the only time that the winning team defeated the European and South American champions alongside the tournament's defending champions. The win gave Brazil its third World Cup title, which allowed them to permanently keep the Jules Rimet Trophy, and a new trophy was introduced in 1974. The victorious team, led by Carlos Alberto and featuring players such as Pelé, Gérson, Jairzinho, Rivellino, and Tostão, is often cited as the greatest-ever football team. They achieved a perfect record of wins in all six games in the finals, as well as winning all their qualifying fixtures. Despite the issues of altitude and high temperature, the finals largely produced attacking football which created an average goals per game record not since bettered by any subsequent World Cup Finals. With the advancements in satellite communications, the 1970 Finals attracted a new record television audience for the FIFA World Cup as games were broadcast live around the world and, in a few cases, in colour—the first time that this was the case.",
        "url": "../image/brazil.png"
    },
    {
        "country": "Germany",
        "year": 1974,
        "text": "The 1974 FIFA World Cup was the tenth FIFA World Cup, a quadrennial football tournament for men's senior national teams, and was played in West Germany (and West Berlin) between 13 June and 7 July. The tournament marked the first time that the current trophy, the FIFA World Cup Trophy, created by the Italian sculptor Silvio Gazzaniga, was awarded. The previous trophy, the Jules Rimet Trophy, had been won for the third time by Brazil in 1970 and awarded permanently to the Brazilians. This was the first out of three World Cups to feature two rounds of group stages. West Germany won the title, beating the Netherlands 2–1 in the final at the Olympiastadion in Munich. This was the second victory for West Germany, who had also won in 1954. Australia, East Germany, Haiti and Zaire made their first appearances at the final stage, with the latter two also making their only appearance, and East Germany making their only appearance before Germany was reunified in 1990.",
        "url": "../image/germany.png"
    },
    {
        "country": "Argentina",
        "year": 1978,
        "text": "The 1978 FIFA World Cup was the 11th edition of the FIFA World Cup, a quadrennial international football world championship tournament among the men's senior national teams. It was held in Argentina between 1 and 25 June. The Cup was won by the host nation, Argentina, who defeated the Netherlands 3–1 in the final, after extra time. The final was held at River Plate's home stadium, Estadio Monumental, in the Argentine capital of Buenos Aires. This win was the first World Cup title for Argentina, who became the fifth team (after Uruguay, Italy, England, and West Germany) to be both hosts and world champions and the third South American team to win a World Cup. Argentina, the Netherlands, and Brazil were the gold, silver, and bronze medalists, respectively. Iran and Tunisia made their first appearances in the tournament. This was also the last World Cup tournament to use the original inclusion of 16 teams. Since the first World Cup in 1930, only 15 teams (plus the host, who automatically qualified) had been allowed to qualify (the reigning title holders also received automatic qualification from 1934 through 2002); but for the next World Cup, in Spain, FIFA expanded that tournament to 24 teams. This tournament was marred by flagrant controversy, domestic politics, and alleged interference and match-fixing by the Argentine authoritarian military junta government, who were using this tournament as an opportunity for nationalistic propaganda, and for the relatively new military junta to seek legitimacy on the world stage.  One player, Ralf Edström, was arrested for speaking to a person in Buenos Aires; however, the Argentine military released him upon recognising its error (that he was a player, not an ordinary person).",
        "url": "../image/argentina.png"
    },
    {
        "country": "Italy",
        "year": 1982,
        "text": "The 1982 FIFA World Cup was the 12th FIFA World Cup, a quadrennial football tournament for men's senior national teams, and was played in Spain between 13 June and 11 July 1982. The tournament was won by Italy, who defeated West Germany 3–1 in the final, held in the Santiago Bernabéu Stadium in the capital, Madrid. It was Italy's third World Cup title, but their first since 1938. The defending champions, Argentina, were eliminated in the second round (finishing third and last in their group). Algeria, Cameroon, Honduras, Kuwait and New Zealand made their first appearances in the finals. The tournament featured the first penalty shoot-out in World Cup competition.   This was the last World Cup to feature two rounds of group stages. It was also the third time (after 1934 and 1966) in which all four semi-finalists were European. In the first round of Group 3, Hungary defeated El Salvador 10–1, equalling the largest margin of victory recorded in the finals (Hungary over South Korea 9–0 in 1954, and Yugoslavia over Zaire 9–0 in 1974). Although successful and filled with compelling and entertaining matches, this tournament was blighted by violent fouls, some poor officiating and some overcrowded stadiums. One particular incident of note was West German goalkeeper Harald Schumacher's foul of French player Patrick Battiston during a semi-final match in Seville, and another was Italian player Claudio Gentile's intense and often violent match-long fouling and marking of Argentine player Diego Maradona. FIFA changed the regulations to somewhat prevent this kind of brutality on the pitch for the subsequent tournament in Mexico.",
        "url": "../image/italy.png"
    },
    {
        "country": "Argentina",
        "year": 1986,
        "text": "The 1986 FIFA World Cup was the 13th FIFA World Cup, a quadrennial football tournament for men's senior national teams. It was played in Mexico from 31 May to 29 June 1986. The tournament was the second to feature a 24-team format. Colombia had been originally chosen to host the competition by FIFA but, largely due to economic reasons, was not able to do so, and resigned in 1982. Mexico was selected as the new host in May 1983, and became the first country to host the World Cup more than once, after previously hosting in 1970. The World Cup was won by Argentina (their second title, after winning in 1978). Argentina was captained by the 25-year-old Diego Maradona, who played a large part in his team's success by scoring his Hand of God goal, as well as another voted Goal of the Century, in the same quarter-final against England. These were two of the five goals that Maradona scored during the tournament, and he also created another five for his teammates.  Argentina beat West Germany 3–2 in the final at Mexico City's Estadio Azteca. Total attendance was 2,394,031, an average per match of 46,039.  Canada, Denmark and Iraq made their first appearances at the final stage. The format of the competition changed from 1982. The final pair of matches in each group started at the same time  and the second round was played on a knock-out basis rather than groups. The 24 teams qualified were divided into six groups of four (A to F). The top two teams and the four best third-place finishers from the six groups advanced to the knockout round of 16 teams. Italy were the defending champions, but were eliminated by France in the Round of 16. The tournament saw the appearance of the Mexican wave, a spectator phenomenon which was popularised worldwide after featuring during the tournament.",
        "url": "../image/argentina.png"
    },
    {
        "country": "Germany",
        "year": 1990,
        "text": "The 1990 FIFA World Cup was the 14th FIFA World Cup, a quadrennial football tournament for men's senior national teams. It was held from 8 June to 8 July 1990 in Italy, the second country to host the event for a second time (the first being Mexico in 1986). Teams representing 116 national football associations entered and qualification began in April 1988. 22 teams qualified from this process, along with host nation Italy and defending champions Argentina. The tournament was won by West Germany, for the third time. They beat Argentina 1–0 at the Stadio Olimpico in Rome, a rematch of the previous final four years earlier. Italy finished third and England fourth, after both lost their semi-finals in penalty shootouts. This was the last tournament to feature a team from West Germany, with the country being reunified with East Germany a few months later in October, as well as teams from the Eastern Bloc prior to the end of the Cold War in 1991, as the Soviet Union and Czechoslovakia teams made last appearances. Costa Rica, Ireland and the United Arab Emirates made their first appearances in the finals. As of 2022, this was the last time the United Arab Emirates qualified for a FIFA World Cup finals. The official match ball was the Adidas Etrusco Unico. The 1990 World Cup is widely regarded as one of the poorest World Cups in terms of the games.    It generated an average 2.21 goals per game – a record low that still stands – and a then-record 16 red cards, including the first dismissal in a final. The tournament also had a significant lasting influence on the game as a whole. In England, the team's success in this tournament led to the resurgence of the domestic top-flight, which had suffered from violence on the pitch and hooliganism by spectators throughout the 1980s. It saw the introduction of the pre-match Fair Play Flag (then inscribed with 'Fair Play Please') to encourage fair play. Overly defensive tactics led to the introduction of the back-pass rule in 1992 and three points for a win instead of two, both of which have encouraged attacking play, increasing spectator interest in the sport. The tournament also produced some of the World Cup's best remembered moments and stories, including the emergence of African nations, in addition to what has become the World Cup soundtrack: 'Nessun dorma'.The 1990 World Cup stands as one of the most watched events in television history, garnering an estimated 26.69 billion non-unique viewers over the course of the tournament. This was the first World Cup to be officially recorded and transmitted in HDTV by the Italian broadcaster RAI in association with Japan's NHK. The huge success of the broadcasting model has also had a lasting impact on the sport. At the time it was the most watched World Cup in history in non-unique viewers, but was bettered by the 1994 and 2002 World Cups.",
        "url": "../image/germany.png"
    },
    {
        "country": "Brazil",
        "year": 1994,
        "text": "The 1994 FIFA World Cup was the 15th FIFA World Cup, the world championship for men's national soccer teams. It was hosted by the United States and took place from June 17 to July 17, 1994, at nine venues across the country. The United States was chosen as the host by FIFA on July 4, 1988. Despite soccer's relative lack of popularity in the host nation, the tournament was the most financially successful   in World Cup history. It broke tournament records with overall attendance of 3,587,538 and an average of 68,991 per game,  marks that stood unsurpassed as of 2022 despite the expansion of the competition from 24 to 32 teams starting with the 1998 World Cup. Brazil was crowned the winner after defeating Italy 3–2 in a penalty shoot-out at the Rose Bowl in Pasadena, California near Los Angeles, after the game had ended 0–0 after extra time. It was the first World Cup final to be decided on penalties. The victory made Brazil the first nation to win four World Cup titles. There were three new entrants in the tournament: Greece, Nigeria and Saudi Arabia; Russia also appeared as a separate nation for the first time, following the breakup of the Soviet Union, and for the first time since 1938, a unified Germany took part in the tournament. They were also defending champions, but were eliminated in quarter-finals by Bulgaria. It was the first World Cup where three points were awarded for a victory instead of two and also the first with the back-pass rule. This was done to encourage a more attacking style of soccer as a response to the criticism of the defensive tactics and low-scoring matches of the 1990 World Cup. This resulted in an average of 2.71 goals per match.",
        "url": "../image/brazil.png"
    },
    {
        "country": "France",
        "year": 1998,
        "text": "The 1998 FIFA World Cup was the 16th FIFA World Cup, the football world championship for men's national teams. The finals tournament was held in France from 10 June to 12 July 1998. The country was chosen as the host nation by FIFA for the second time in the history of the tournament, defeating Morocco in the bidding process. It was the second time that France staged the competition (the first was in 1938) and the ninth time that it was held in Europe. Spanning 32 days, it is the longest World Cup tournament ever held. Qualification for the finals began in March 1996 and concluded in November 1997. For the first time in the competition, the group stage was expanded from 24 teams to 32, with eight groups of four. 64 matches were played in 10 stadiums in 10 host cities, with the opening match and final staged at the newly built Stade de France in the Parisian commune of Saint-Denis. The tournament was won by host country France, who beat defending champions Brazil 3–0 in the final. France won their first title, becoming the seventh nation to win a World Cup, and the sixth (after Uruguay, Italy, England, West Germany and Argentina) and as of 2022 the most recent to win the tournament on home soil. Croatia, Jamaica, Japan and South Africa made their first appearances in the finals.",
        "url": "../image/france.png"
    },
    {
        "country": "Brazil",
        "year": 2002,
        "text": "The 2002 FIFA World Cup, also branded as Korea Japan 2002, was the 17th FIFA World Cup, the quadrennial football world championship for men's national teams organized by FIFA. It was held from 31 May to 30 June 2002 at sites in South Korea and Japan, with its final match hosted by Japan at International Stadium in Yokohama. A field of 32 teams qualified for this World Cup, which was the first to be held in Asia, the first to be held outside of the Americas or Europe, as well as the first to be jointly-hosted by more than one nation. China, Ecuador, Senegal, and Slovenia made their World Cup debuts. The tournament had several upsets and surprise results, which included the defending champions France being eliminated in the group stage after earning a single point without scoring a goal and second favourites Argentina also being eliminated in the group stage. South Korea managed to reach the semi-finals, beating Poland, Portugal, Italy and Spain en route. They became the first team from outside of the UEFA, CONMEBOL, and CONCACAF regions to reach the semi-finals of a World Cup. However, the most potent team at the tournament, Brazil, prevailed, winning the final against Germany 2–0, making them the first and only country to have won the World Cup five times.  The victory qualified Brazil for the 2003 and subsequently 2005 FIFA Confederations Cups, its fourth and fifth Confederations Cup appearance in a row. In the third place play-off match against South Korea, Turkey won 3–2, taking third place in only their second ever FIFA World Cup, and scored the fastest goal in the FIFA World Cup history (10.8 seconds after kick-off).  The 2002 World Cup was also the last one to use the golden goal rule and the last one to use the same ball for all matches. Starting in 2006 and continuing to the present, a ball with the same technical specifics but different colors has been used in the final.",
        "url": "../image/brazil.png"
    },
    {
        "country": "Italy",
        "year": 2006,
        "text": "The 2006 FIFA World Cup, also branded as Germany 2006, was the 18th FIFA World Cup, the quadrennial international football world championship tournament. It was held from 9 June to 9 July 2006 in Germany, which had won the right to host the event in July 2000. Teams representing 198 national football associations from all six populated continents participated in the qualification process which began in September 2003. Thirty-one teams qualified from this process along with hosts Germany for the finals tournament. It was the second time that Germany staged the competition and the first as a unified country along with the former East Germany with Leipzig as a host city (the other was in 1974 in West Germany), and the 10th time that the tournament was held in Europe. Italy won the tournament, claiming their fourth World Cup title, defeating France 5–3 in a penalty shoot-out in the final after extra time had finished in a 1–1 draw. Germany defeated Portugal 3–1 to finish in third place. Angola, Ghana, the Ivory Coast, Trinidad and Tobago and Togo made their first appearances in the finals. It was also the only appearance of Serbia and Montenegro under that name; they had previously appeared in 1998 as Yugoslavia. In late May 2006, immediately prior to the tournament, Montenegro voted in a referendum to become an independent nation and dissolve the loose confederacy then existing between it and Serbia; Serbia recognised the results of the referendum in early June. Due to time constraints, FIFA had Serbia and Montenegro play in the World Cup tournament as one team, marking the first instance of multiple sovereign nations competing as one team in a major football tournament since UEFA Euro 1992. The 2006 World Cup stands as one of the most watched events in television history, garnering an estimated 26.29 billion times viewed compiled over the course of the tournament. The final attracted an estimated audience of 715.1 million people. ",
        "url": "../image/italy.png"
    },
    {
        "country": "Spain",
        "year": 2010,
        "text": "The 2010 FIFA World Cup, also branded as South Africa 2010, was the 19th FIFA World Cup, the world championship for men's national football teams. It took place in South Africa from 11 June to 11 July 2010. The bidding process for hosting the tournament finals was open only to African nations. In 2004, the international football federation, FIFA, selected South Africa over Egypt and Morocco to become the first African nation to host the finals. The matches were played in 10 stadiums in nine host cities around the country, with the opening and final played at the Soccer City stadium in South Africa's largest city, Johannesburg. Thirty-two teams were selected for participation via a worldwide qualification tournament that began in August 2007. In the first round of the tournament finals, the teams competed in round-robin groups of four teams for points, with the top two teams in each group proceeding. These 16 teams advanced to the knockout stage, where three rounds of play decided which teams would participate in the final. In the final, Spain, the European champions, defeated third-time losing finalists the Netherlands 1–0 after extra time to win their first world title. Spain became the eighth nation to win the tournament and the first European nation to win a World Cup hosted outside its home continent: all previous World Cups held outside Europe had been won by South American nations. They are also the first national team since 1978 to win a World Cup after losing a game in the group stage. As a result of their win, Spain represented the World in the 2013 FIFA Confederations Cup. Host nation South Africa were eliminated in the group stage along with both 2006 World Cup finalists Italy and France. It was the first time that the hosts had been eliminated in the first stage. New Zealand, with their three draws, were the only undefeated team in the tournament, but they were also eliminated in the group stage.",
        "url": "../image/spain.png"
    },
    {
        "country": "Germany",
        "year": 2014,
        "text": "The 2014 FIFA World Cup was the 20th FIFA World Cup, the quadrennial world championship for men's national football teams organised by FIFA. It took place in Brazil from 12 June to 13 July 2014, after the country was awarded the hosting rights in 2007. It was the second time that Brazil staged the competition, the first being in 1950, and the fifth time that it was held in South America. 31 national teams advanced through qualification competitions to join the host nation in the final tournament (with Bosnia and Herzegovina as the only debutant). A total of 64 matches were played in 12 venues located in as many host cities across Brazil. For the first time at a World Cup finals, match officials used goal-line technology, as well as vanishing spray for free kicks. FIFA Fan Fests in each host city gathered a total of 5 million people, and the country received 1 million visitors from 202 countries. Every World Cup-winning team since the first tournament in 1930 – Argentina, Brazil, England, France, Germany, Italy, Spain and Uruguay – qualified for this tournament, for the last time to date. Spain, the defending champions, were eliminated at the group stage, along with England and Italy. Uruguay were eliminated in the round of 16, and France exited in the quarter-finals. Host nation Brazil, who had won the 2013 FIFA Confederations Cup, lost to Germany 7–1 in the semi-finals and eventually finished in fourth place. In the final, Germany defeated Argentina 1–0 after extra time thanks to a Mario Götze half-volley in the 113th minute of the final to win the tournament and secure the country's fourth world title, the first after German reunification in 1990, when as West Germany they also beat Argentina by the same score in 90 minutes in the World Cup final. Germany became the first European team to win a World Cup staged in the Americas, and this result marked the third consecutive title won by a European team, after Italy in 2006 and Spain in 2010.",
        "url": "../image/germany.png"
    },
    {
        "country": "France",
        "year": 2018,
        "text": "The 2018 FIFA World Cup was the 21st FIFA World Cup, the quadrennial world championship for national football teams organized by FIFA. It took place in Russia from 14 June to 15 July 2018, after the country was awarded the hosting rights in 2010. It was the eleventh time the championships had been held in Europe, and the first time they were held in Eastern Europe. At an estimated cost of over $14.2 billion, it was the most expensive World Cup ever held until it was surpassed by the 2022 World Cup in Qatar. The tournament phase involved 32 teams, of which 31 came through qualifying competitions, while as the host nation Russia qualified automatically. Of the 32, 20 had also appeared in the 2014 event, while Iceland and Panama each made their first appearance at the World Cup. 64 matches were played in 12 venues across 11 cities. Germany, the defending champions, were eliminated in the group stage for the first time since 1938. Host nation Russia was eliminated in the quarter-finals. In the final, France played Croatia on 15 July at the Luzhniki Stadium in Moscow. France won the match 4–2, claiming their second World Cup and becoming the fourth consecutive title won by a European team, after Italy in 2006, Spain in 2010, and Germany in 2014. Croatian player Luka Modrić was voted the tournament's best player, winning the Golden Ball. England's Harry Kane won the Golden Boot as he scored the most goals during the tournament with six. Belgium's Thibaut Courtois won the Golden Glove, awarded to the goalkeeper with the best performance. It has been estimated that more than 3 million people attended games during the tournament.",
        "url": "../image/france.png"
    },
    {
        "country": "Argentina",
        "year": 2022,
        "text": "The 2022 FIFA World Cup was an international football tournament contested by the men's national teams of FIFA's member associations and 22nd edition of the FIFA World Cup. It took place in Qatar from 20 November to 18 December 2022, making it the first World Cup held in the Arab world and Muslim world, and the second held entirely in Asia after the 2002 tournament in South Korea and Japan. This tournament was the last with 32 participating teams, with the number of teams being increased to 48 for the 2026 edition. To avoid the extremes of Qatar's hot climate, the event was held during November and December. It was held over a reduced time frame of 29 days with 64 matches played in eight venues across five cities. Qatar entered the event—their first World Cup—automatically as the host's national team, alongside 31 teams determined by the qualification process. Argentina were crowned the champions after winning the final against the title holder France 4–2 on penalties following a 3–3 draw after extra time. It was Argentina's third title and their first since 1986, as well being the first nation from outside of Europe to win the tournament since 2002. French player Kylian Mbappé became the first player to score a hat-trick in a World Cup final since Geoff Hurst in the 1966 final and won the Golden Boot as he scored the most goals (eight) during the tournament. Argentine captain Lionel Messi was voted the tournament's best player, winning the Golden Ball. Teammates Emiliano Martínez and Enzo Fernández won the Golden Glove, awarded to the tournament's best goalkeeper, and the Young Player Award, awarded to the tournament's best young player, respectively. The tournament, with 172 goals, set a new record for the highest number of goals scored with the 32 team format. The choice to host the World Cup in Qatar attracted significant criticism, with concerns raised over the country's treatment of migrant workers, women and members of the LGBT community, as well as Qatar's climate, lack of a strong football culture, scheduling changes, and allegations of bribery for hosting rights and wider FIFA corruption.",
        "url": "../image/argentina.png"
    }
]

export default data;